# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

service: tg-repository

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_USERS_TABLE: ${self:service}-${self:provider.stage}-users
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_USERS_TABLE}"

functions:
  graphql:
    handler: handler.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: telegramId
            AttributeType: S
        KeySchema:
          -
            AttributeName: telegramId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_USERS_TABLE}

plugins:
  - serverless-dynamodb-local
